services:

  mongodb:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      # See https://docs.docker.com/storage/volumes/
      #
      # The 'Z' option tells Docker to label the content with a
      # private unshared label. Private volumes can only be used by
      # the current container.  See
      # https://docs.docker.com/engine/reference/commandline/run/
      - type: volume
        source: mongodb
        target: /data/db:Z
    healthcheck:
      test: ["CMD", "mongosh", "localhost:27017/test", "--quiet"]

  sdx-lc:
    image: sdx-lc
    tty: true
    build: ./
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        # Anther condition is `service_healthy`, and it will require
        # the `healthcheck` above.
        condition: service_started
    environment:
      # connect to the mongodb service started by compose.
      - MONGODB_CONNSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      - SDXLC_DOMAIN=${SDXLC_DOMAIN}
      # change to local controller host name
      - SDXLC_HOST=${SDXLC_HOST}
      - SDXLC_PORT=${SDXLC_PORT}
      - SDXLC_VERSION=${SDXLC_VERSION}
      - SUB_QUEUE=${SUB_QUEUE}
      - SUB_EXCHANGE=${SUB_EXCHANGE}
      # change to local controller config (lcX_q1)
      - SUB_TOPIC=${SUB_TOPIC}
      - MQ_NAME=${MQ_NAME}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - MQ_USER=${MQ_USER}
      - MQ_PASS=${MQ_PASS}
      - DB_NAME=${DB_NAME}
      - DB_CONFIG_TABLE_NAME=${DB_CONFIG_TABLE_NAME}
      - OXP_CONNECTION_URL=${OXP_CONNECTION_URL}
      - OXP_PULL_URL=${OXP_PULL_URL}
      - OXP_PULL_INTERVAL=${OXP_PULL_INTERVAL}
      - OXP_CONNECTION_URL=${OXP_CONNECTION_URL}

volumes:
  mongodb:
