version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    # image: rabbitmq:latest
    # container_name: simple-mq
    hostname: rabbitmq-container
    #volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sdxnet

  sdx-controller:
    image: sdx-lc
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      - SDX_MQ_IP=152.54.3.143
      - SDXLC_HOST=aw-sdx-lc-1.renci.org
      - SDXLC_PORT=8080
      - SDXLC_VERSION=1.0.0
      - MQ_NAME=hello
      - MQ_HOST=aw-sdx-monitor.renci.org
      - MQ_PORT=5672 
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=test-1
    networks:
      - sdxnet

networks:
  sdxnet:
    external:
      name: sdxnet

