version: '3.8'

services:

  my-mongodb:
    image: mongo:3.7
    container_name: mongodb-lc
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
    volumes:
      # named volumes
      - ~/mongodb:/data/db

  sdx-lc:
    image: sdx-lc
    container_name: sdx-lc
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNSTRING=${MONGODB_CONNSTRING}
      - SDX_MQ_IP=${SDX_MQ_IP}
      - SDXLC_DOMAIN=${SDXLC_DOMAIN}
      # change to local controller host name
      - SDXLC_HOST=${SDXLC_HOST}
      - SDXLC_PORT=${SDXLC_PORT}
      - SDXLC_VERSION=${SDXLC_VERSION}
      - PUB_TOPIC=${PUB_TOPIC}
      - PUB_QUEUE=${PUB_QUEUE}
      - SUB_QUEUE=${SUB_QUEUE}
      - SUB_EXCHANGE=${SUB_EXCHANGE}
      # change to local controller config (lcX_q1)
      - SUB_TOPIC=${SUB_TOPIC}
      - MQ_NAME=${MQ_NAME}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - DB_NAME=${DB_NAME}
      - DB_CONFIG_TABLE_NAME=${DB_CONFIG_TABLE_NAME}
      - OXP_CONNECTION_URL=${OXP_CONNECTION_URL}
      - OXP_PULL_URL=${OXP_PULL_URL}
      - OXP_PULL_INTERVAL=${OXP_PULL_INTERVAL}
      - OXP_CONNECTION_URL=${OXP_CONNECTION_URL}
