version: '3.8'

services:
  sdx-lc:
    image: sdx-lc
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      - SDX_MQ_IP=152.54.3.143
      - SDXLC_DOMAIN=amlight
      # change to local controller host name
      - SDXLC_HOST=aw-sdx-lc-1.renci.org
      - SDXLC_PORT=8080
      - SDXLC_VERSION=1.0.0
      - PUB_TOPIC=topo
      - PUB_QUEUE=sdx_q1
      - SUB_QUEUE=connection
      - SUB_EXCHANGE=connection
      # change to local controller config (lcX_q1)
      - SUB_TOPIC=lc1_q1
      - MQ_NAME=hello
      - MQ_HOST=aw-sdx-monitor.renci.org
      - MQ_PORT=5672 
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=test-1
      - KYTOS_URL=http://192.168.201.205:8088/SDX-LC/1.0.0/provision
