# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.new_provisioning import NewProvisioning  # noqa: F401,E501
from swagger_server import util


class Provisioning(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Provisioning - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Provisioning':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Provisioning of this Provisioning.  # noqa: E501
        :rtype: Provisioning
        """
        return util.deserialize_model(dikt, cls)
